---
- hosts: all
  tasks:
    - name: Check if Service Exists
      stat: path=/etc/init.d/mssql-server
      register: service_status

    - name: Stop Service
      service: name={{service_name}} state=stopped
      when: service_status.stat.exists
      register: service_stopped
    
    - name:
      yum:
        name: mssql-server
        state: absent
        
    - name: Ansible delete mssql files
      file: path="/var/opt/mssql/" state=absent
        

