---
- hosts: all
  tasks:
    - name: stop ms sql server
      systemd:
        name: mssql-server
        state: stopped
        enabled: no
        
    - name:
      yum:
        name: mssql-server
        state: absent
        
    - name: Ansible delete mssql files
      shell: rm -rf /var/opt/mssql/
        

